# str1 = ("my name is sohail .\n my age is 32")
# print (print (str1))
# str2 = ("my name is sohail.\ tmy age is 32")
# print (str2)
# str1 = ("arslan our sohail ")
# str2 = ("dost hyen .")
# str1 = (" arsln our sohal ")
# str2 = ("dost thy .")
# print (str1+str2)
# str1 = ("sohail riaz")
# print (str1[1:3]) 
# str1 = ("i am a coder")
# print (str1.endswith("er"))
# print (str1. replace ("a","o"))
# print (str1.find("a"))
# print (str1.count("a"))